const vocabulary = {

lesson1:{
main:[
{jp:"わたし",romaji:"watashi",en:"I"},
{jp:"あなた",romaji:"anata",en:"you"},
{jp:"あのひと",romaji:"ano hito",en:"that person"},
{jp:"あのかた",romaji:"ano kata",en:"that person (polite)"},
{jp:"みなさん",romaji:"minasan",en:"everyone"},
{jp:"～さん",romaji:"san",en:"Mr / Ms"},
{jp:"～ちゃん",romaji:"chan",en:"child suffix"},
{jp:"～くん",romaji:"kun",en:"boy suffix"},
{jp:"～じん",romaji:"jin",en:"nationality suffix"},
{jp:"せんせい",romaji:"sensei",en:"teacher"},
{jp:"きょうし",romaji:"kyoushi",en:"instructor"},
{jp:"がくせい",romaji:"gakusei",en:"student"},
{jp:"かいしゃいん",romaji:"kaishain",en:"company employee"},
{jp:"しゃいん",romaji:"shain",en:"employee"},
{jp:"ぎんこういん",romaji:"ginkouin",en:"bank employee"},
{jp:"いしゃ",romaji:"isha",en:"doctor"},
{jp:"けんきゅうしゃ",romaji:"kenkyuusha",en:"researcher"},
{jp:"エンジニア",romaji:"enjinia",en:"engineer"},
{jp:"だいがく",romaji:"daigaku",en:"university"},
{jp:"びょういん",romaji:"byouin",en:"hospital"},
{jp:"だれ",romaji:"dare",en:"who"},
{jp:"どなた",romaji:"donata",en:"who (polite)"},
{jp:"～さい",romaji:"sai",en:"years old"},
{jp:"なんさい",romaji:"nansai",en:"how old"},
{jp:"おいくつ",romaji:"oikutsu",en:"how old (polite)"},
{jp:"はい",romaji:"hai",en:"yes"},
{jp:"いいえ",romaji:"iie",en:"no"},
{jp:"しつれいですが",romaji:"shitsurei desu ga",en:"excuse me"},
{jp:"おなまえは",romaji:"onamae wa",en:"your name"},
{jp:"はじめまして",romaji:"hajimemashite",en:"nice to meet you"},
{jp:"どうぞよろしく",romaji:"douzo yoroshiku",en:"please treat me well"},
{jp:"こちらこそよろしく",romaji:"kochira koso yoroshiku",en:"same to you"}
],
extra:[]
},

lesson2:{
main:[
{jp:"これ",romaji:"kore",en:"this"},
{jp:"それ",romaji:"sore",en:"that"},
{jp:"あれ",romaji:"are",en:"that over there"},
{jp:"この",romaji:"kono",en:"this (before noun)"},
{jp:"その",romaji:"sono",en:"that (before noun)"},
{jp:"あの",romaji:"ano",en:"that over there (before noun)"},
{jp:"ほん",romaji:"hon",en:"book"},
{jp:"じしょ",romaji:"jisho",en:"dictionary"},
{jp:"ざっし",romaji:"zasshi",en:"magazine"},
{jp:"しんぶん",romaji:"shinbun",en:"newspaper"},
{jp:"ノート",romaji:"nooto",en:"notebook"},
{jp:"てちょう",romaji:"techou",en:"memo pad"},
{jp:"めいし",romaji:"meishi",en:"business card"},
{jp:"カード",romaji:"kaado",en:"card"},
{jp:"テレホンカード",romaji:"terehon kaado",en:"telephone card"},
{jp:"えんぴつ",romaji:"enpitsu",en:"pencil"},
{jp:"ボールペン",romaji:"boorupen",en:"ballpoint pen"},
{jp:"シャープペンシル",romaji:"shaapupenshiru",en:"mechanical pencil"},
{jp:"かぎ",romaji:"kagi",en:"key"},
{jp:"とけい",romaji:"tokei",en:"watch"},
{jp:"かさ",romaji:"kasa",en:"umbrella"},
{jp:"かばん",romaji:"kaban",en:"bag"},
{jp:"テープ",romaji:"teepu",en:"tape"},
{jp:"テープレコーダー",romaji:"teepurekoodaa",en:"tape recorder"},
{jp:"テレビ",romaji:"terebi",en:"television"},
{jp:"ラジオ",romaji:"rajio",en:"radio"},
{jp:"カメラ",romaji:"kamera",en:"camera"},
{jp:"コンピューター",romaji:"konpyuutaa",en:"computer"},
{jp:"くるま",romaji:"kuruma",en:"car"},
{jp:"つくえ",romaji:"tsukue",en:"desk"},
{jp:"いす",romaji:"isu",en:"chair"},
{jp:"チョコレート",romaji:"chokoreeto",en:"chocolate"},
{jp:"コーヒー",romaji:"koohii",en:"coffee"},
{jp:"えいご",romaji:"eigo",en:"English language"},
{jp:"にほんご",romaji:"nihongo",en:"Japanese language"},
{jp:"～ご",romaji:"go",en:"language suffix"},
{jp:"なん",romaji:"nan",en:"what"},
{jp:"そう",romaji:"sou",en:"so"},
{jp:"ちがいます",romaji:"chigaimasu",en:"not correct / different"},
{jp:"そうですか",romaji:"sou desu ka",en:"I see"}
],
extra:[]
},

lesson3:{
main:[
{jp:"ここ",romaji:"koko",en:"here"},
{jp:"そこ",romaji:"soko",en:"there"},
{jp:"あそこ",romaji:"asoko",en:"over there"},
{jp:"どこ",romaji:"doko",en:"where"},
{jp:"こちら",romaji:"kochira",en:"this way"},
{jp:"そちら",romaji:"sochira",en:"that way"},
{jp:"あちら",romaji:"achira",en:"that way over there"},
{jp:"どちら",romaji:"dochira",en:"which way"},
{jp:"きょうしつ",romaji:"kyoushitsu",en:"classroom"},
{jp:"しょくどう",romaji:"shokudou",en:"cafeteria"},
{jp:"じむしょ",romaji:"jimusho",en:"office"},
{jp:"かいぎしつ",romaji:"kaigishitsu",en:"meeting room"},
{jp:"うけつけ",romaji:"uketsuke",en:"reception"},
{jp:"ロビー",romaji:"robii",en:"lobby"},
{jp:"へや",romaji:"heya",en:"room"},
{jp:"トイレ",romaji:"toire",en:"toilet"},
{jp:"おてあらい",romaji:"otearai",en:"washroom"},
{jp:"かいだん",romaji:"kaidan",en:"stairs"},
{jp:"エレベーター",romaji:"erebeetaa",en:"elevator"},
{jp:"エスカレーター",romaji:"esukareetaa",en:"escalator"},
{jp:"くに",romaji:"kuni",en:"country"},
{jp:"かいしゃ",romaji:"kaisha",en:"company"},
{jp:"うち",romaji:"uchi",en:"home"},
{jp:"でんわ",romaji:"denwa",en:"telephone"},
{jp:"くつ",romaji:"kutsu",en:"shoes"},
{jp:"ネクタイ",romaji:"nekutai",en:"tie"},
{jp:"ワイン",romaji:"wain",en:"wine"},
{jp:"うりば",romaji:"uriba",en:"sales floor"},
{jp:"ちか",romaji:"chika",en:"basement"},
{jp:"いくら",romaji:"ikura",en:"how much"}
],
extra:[]
},

lesson4:{
main:[
{jp:"いま",romaji:"ima",en:"now"},
{jp:"～じ",romaji:"ji",en:"hour"},
{jp:"～ふん",romaji:"fun",en:"minute"},
{jp:"はん",romaji:"han",en:"half"},
{jp:"なんじ",romaji:"nanji",en:"what time"},
{jp:"なんぷん",romaji:"nanpun",en:"what minute"},
{jp:"ごぜん",romaji:"gozen",en:"AM"},
{jp:"ごご",romaji:"gogo",en:"PM"},
{jp:"あさ",romaji:"asa",en:"morning"},
{jp:"ひる",romaji:"hiru",en:"daytime"},
{jp:"ばん",romaji:"ban",en:"evening"},
{jp:"よる",romaji:"yoru",en:"night"},
{jp:"きのう",romaji:"kinou",en:"yesterday"},
{jp:"きょう",romaji:"kyou",en:"today"},
{jp:"あした",romaji:"ashita",en:"tomorrow"},
{jp:"まいあさ",romaji:"maiasa",en:"every morning"},
{jp:"まいばん",romaji:"maiban",en:"every night"},
{jp:"いきます",romaji:"ikimasu",en:"go"},
{jp:"きます",romaji:"kimasu",en:"come"},
{jp:"かえります",romaji:"kaerimasu",en:"return"},
{jp:"べんきょうします",romaji:"benkyoushimasu",en:"study"},
{jp:"はたらきます",romaji:"hatarakimasu",en:"work"},
{jp:"やすみます",romaji:"yasumimasu",en:"rest"},
{jp:"おきます",romaji:"okimasu",en:"wake up"},
{jp:"ねます",romaji:"nemasu",en:"sleep"}
],
extra:[]
},

lesson5:{
main:[
{jp:"いきます",romaji:"ikimasu",en:"go"},
{jp:"きます",romaji:"kimasu",en:"come"},
{jp:"かえります",romaji:"kaerimasu",en:"return"},
{jp:"がっこう",romaji:"gakkou",en:"school"},
{jp:"スーパー",romaji:"suupaa",en:"supermarket"},
{jp:"えき",romaji:"eki",en:"station"},
{jp:"ひこうき",romaji:"hikouki",en:"airplane"},
{jp:"ふね",romaji:"fune",en:"ship"},
{jp:"でんしゃ",romaji:"densha",en:"train"},
{jp:"バス",romaji:"basu",en:"bus"},
{jp:"タクシー",romaji:"takushii",en:"taxi"},
{jp:"じてんしゃ",romaji:"jitensha",en:"bicycle"},
{jp:"あるいて",romaji:"aruite",en:"on foot"},
{jp:"ひと",romaji:"hito",en:"person"},
{jp:"ともだち",romaji:"tomodachi",en:"friend"},
{jp:"かれ",romaji:"kare",en:"he"},
{jp:"かのじょ",romaji:"kanojo",en:"she"},
{jp:"かぞく",romaji:"kazoku",en:"family"},
{jp:"ひとりで",romaji:"hitoride",en:"alone"},
{jp:"せんしゅう",romaji:"senshuu",en:"last week"},
{jp:"こんしゅう",romaji:"konshuu",en:"this week"},
{jp:"らいしゅう",romaji:"raishuu",en:"next week"},
{jp:"せんげつ",romaji:"sengetsu",en:"last month"},
{jp:"こんげつ",romaji:"kongetsu",en:"this month"},
{jp:"らいげつ",romaji:"raigetsu",en:"next month"},
{jp:"きのう",romaji:"kinou",en:"yesterday"},
{jp:"きょう",romaji:"kyou",en:"today"},
{jp:"あした",romaji:"ashita",en:"tomorrow"}
],
extra:[]
}
