const vocabulary = {

lesson1:{
main:[
{jp:"わたし",romaji:"watashi",en:"I"},
{jp:"あなた",romaji:"anata",en:"you"},
{jp:"あのひと",romaji:"ano hito",en:"that person"},
{jp:"あのかた",romaji:"ano kata",en:"that person (polite)"},
{jp:"みなさん",romaji:"minasan",en:"everyone"},
{jp:"～さん",romaji:"san",en:"Mr / Ms"},
{jp:"～ちゃん",romaji:"chan",en:"child suffix"},
{jp:"～くん",romaji:"kun",en:"boy suffix"},
{jp:"～じん",romaji:"jin",en:"nationality suffix"},
{jp:"せんせい",romaji:"sensei",en:"teacher"},
{jp:"きょうし",romaji:"kyoushi",en:"instructor"},
{jp:"がくせい",romaji:"gakusei",en:"student"},
{jp:"かいしゃいん",romaji:"kaishain",en:"company employee"},
{jp:"しゃいん",romaji:"shain",en:"employee"},
{jp:"ぎんこういん",romaji:"ginkouin",en:"bank employee"},
{jp:"いしゃ",romaji:"isha",en:"doctor"},
{jp:"けんきゅうしゃ",romaji:"kenkyuusha",en:"researcher"},
{jp:"エンジニア",romaji:"enjinia",en:"engineer"},
{jp:"だいがく",romaji:"daigaku",en:"university"},
{jp:"びょういん",romaji:"byouin",en:"hospital"},
{jp:"だれ",romaji:"dare",en:"who"},
{jp:"どなた",romaji:"donata",en:"who (polite)"},
{jp:"～さい",romaji:"sai",en:"years old"},
{jp:"なんさい",romaji:"nansai",en:"how old"},
{jp:"おいくつ",romaji:"oikutsu",en:"how old (polite)"},
{jp:"はい",romaji:"hai",en:"yes"},
{jp:"いいえ",romaji:"iie",en:"no"},
{jp:"しつれいですが",romaji:"shitsurei desu ga",en:"excuse me"},
{jp:"おなまえは",romaji:"onamae wa",en:"your name"},
{jp:"はじめまして",romaji:"hajimemashite",en:"nice to meet you"},
{jp:"どうぞよろしく",romaji:"douzo yoroshiku",en:"please treat me well"},
{jp:"こちらこそよろしく",romaji:"kochira koso yoroshiku",en:"same to you"}
],
extra:[]
},

lesson2:{
main:[
{jp:"これ",romaji:"kore",en:"this"},
{jp:"それ",romaji:"sore",en:"that"},
{jp:"あれ",romaji:"are",en:"that over there"},
{jp:"この",romaji:"kono",en:"this (before noun)"},
{jp:"その",romaji:"sono",en:"that (before noun)"},
{jp:"あの",romaji:"ano",en:"that over there (before noun)"},
{jp:"ほん",romaji:"hon",en:"book"},
{jp:"じしょ",romaji:"jisho",en:"dictionary"},
{jp:"ざっし",romaji:"zasshi",en:"magazine"},
{jp:"しんぶん",romaji:"shinbun",en:"newspaper"},
{jp:"ノート",romaji:"nooto",en:"notebook"},
{jp:"てちょう",romaji:"techou",en:"memo pad"},
{jp:"めいし",romaji:"meishi",en:"business card"},
{jp:"カード",romaji:"kaado",en:"card"},
{jp:"テレホンカード",romaji:"terehon kaado",en:"telephone card"},
{jp:"えんぴつ",romaji:"enpitsu",en:"pencil"},
{jp:"ボールペン",romaji:"boorupen",en:"ballpoint pen"},
{jp:"シャープペンシル",romaji:"shaapupenshiru",en:"mechanical pencil"},
{jp:"かぎ",romaji:"kagi",en:"key"},
{jp:"とけい",romaji:"tokei",en:"watch"},
{jp:"かさ",romaji:"kasa",en:"umbrella"},
{jp:"かばん",romaji:"kaban",en:"bag"},
{jp:"テープ",romaji:"teepu",en:"tape"},
{jp:"テープレコーダー",romaji:"teepurekoodaa",en:"tape recorder"},
{jp:"テレビ",romaji:"terebi",en:"television"},
{jp:"ラジオ",romaji:"rajio",en:"radio"},
{jp:"カメラ",romaji:"kamera",en:"camera"},
{jp:"コンピューター",romaji:"konpyuutaa",en:"computer"},
{jp:"くるま",romaji:"kuruma",en:"car"},
{jp:"つくえ",romaji:"tsukue",en:"desk"},
{jp:"いす",romaji:"isu",en:"chair"},
{jp:"チョコレート",romaji:"chokoreeto",en:"chocolate"},
{jp:"コーヒー",romaji:"koohii",en:"coffee"},
{jp:"えいご",romaji:"eigo",en:"English language"},
{jp:"にほんご",romaji:"nihongo",en:"Japanese language"},
{jp:"～ご",romaji:"go",en:"language suffix"},
{jp:"なん",romaji:"nan",en:"what"},
{jp:"そう",romaji:"sou",en:"so"},
{jp:"ちがいます",romaji:"chigaimasu",en:"not correct / different"},
{jp:"そうですか",romaji:"sou desu ka",en:"I see"},
{jp:"あのう",romaji:"anou",en:"well / excuse me"},
{jp:"ほんのきもちです",romaji:"honno kimochi desu",en:"small gift"},
{jp:"どうぞ",romaji:"douzo",en:"please"},
{jp:"どうも",romaji:"doumo",en:"thanks"},
{jp:"ありがとうございます",romaji:"arigatou gozaimasu",en:"thank you"},
{jp:"どうもありがとうございます",romaji:"doumo arigatou gozaimasu",en:"thank you very much"},
{jp:"これからおせわになります",romaji:"korekara osewa ni narimasu",en:"please take care of me"},
{jp:"こちらこそよろしく",romaji:"kochira koso yoroshiku",en:"same to you"},
{jp:"よろしくおねがいします",romaji:"yoroshiku onegaishimasu",en:"please treat me well"},
{jp:"こちら",romaji:"kochira",en:"this way"},
{jp:"どれ",romaji:"dore",en:"which"},
{jp:"どの",romaji:"dono",en:"which (before noun)"}
],
extra:[]
}

}
